### PR TITLE
DOCUMENTATIONS: Add Exceptions for Language Service

### LINKED ISSUE #242: DOCUMENTATIONS: Add Exceptions for Language Service

### PR DESCRIPTION
**Pull request by devdoston**
Closes #242

### CODE REVIEW

File: CashOverflow/Services/Foundations/Languages/ILanguageService.cs [hunk 1]
```diff
@@ -12,10 +12,28 @@ namespace CashOverflow.Services.Foundations.Languages
...
+        /// <exception cref="Models.Languages.Exceptions.LanguageDependencyException"></exception>
         IQueryable<Language> RetrieveAllLanguages();
+
+        /// <exception cref="Models.Languages.Exceptions.LanguageServiceException"></exception>
+        /// <exception cref="Models.Languages.Exceptions.LanguageDependencyException"></exception>
         ValueTask<Language> RetrieveLanguageByIdAsync(Guid languageId);
+
+        /// <exception cref="Models.Languages.Exceptions.LanguageServiceException"></exception>
+        /// <exception cref="Models.Languages.Exceptions.LanguageDependencyException"></exception>
+        /// <exception cref="Models.Languages.Exceptions.LanguageDependencyValidationException"></exception>
```
Comment (ElbekDeveloper) [inline CashOverflow/Services/Foundations/Languages/ILanguageService.cs:31]: Bunda language validation exception qaytarilmas ekanmi?

**Review by ElbekDeveloper — APPROVED** [review]
